In [2]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:

print(arr.dtype)

int64


In [9]:
arr2=np.array([1,2,3,4,5],dtype=np.int16)
            

In [10]:
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [12]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])



In [13]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
ar1 = np.array([5,5])
ar1

array([5, 5])

In [17]:
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
o1=np.ones([5,5])

In [19]:
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
I=np.eye(5)

In [21]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
r1=np.random.rand(4,5)
r1

array([[0.73048355, 0.38485191, 0.56929349, 0.49182308, 0.93127495],
       [0.87748512, 0.01473083, 0.82951051, 0.57282958, 0.03167722],
       [0.10030159, 0.59338942, 0.80526018, 0.35594161, 0.80631292],
       [0.66355189, 0.0618508 , 0.10924086, 0.50463172, 0.9842867 ]])

In [24]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
print(ar2.size)

9


In [32]:
print(ar2.shape)

(3, 3)


# Operations in Array
**COPY**

**SORT**

**RESHAPE**

In [33]:
ar3=np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar3[2,2]=10
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [35]:
ar3[1,2]=12
ar3[0,1]=15

In [36]:
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [38]:
ar3=np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [39]:
ar3=np.sort(ar3,axis=0)
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [40]:
ar3.sum()

np.int64(65)

In [41]:
ar3.sum(axis=0)

array([12, 16, 37])

In [42]:
ar3.sum(axis=1)

array([14, 21, 30])

In [43]:
ar4=np.random.rand(99)
ar4

array([0.98705175, 0.74422132, 0.18351423, 0.57272625, 0.96688545,
       0.48129732, 0.38639498, 0.73232965, 0.60912908, 0.6022489 ,
       0.84213446, 0.58390546, 0.41510508, 0.55678095, 0.58955392,
       0.96937221, 0.90621632, 0.89905986, 0.93664397, 0.47498988,
       0.04128258, 0.72282523, 0.19993304, 0.3083793 , 0.38296473,
       0.87088531, 0.62877058, 0.45281169, 0.61773935, 0.81031362,
       0.25492709, 0.50411477, 0.63299886, 0.53451714, 0.76921127,
       0.74387326, 0.61976393, 0.79898007, 0.60865704, 0.29779564,
       0.60907677, 0.13902574, 0.42704775, 0.03010767, 0.89720725,
       0.09023026, 0.48261823, 0.5995653 , 0.52835164, 0.81413172,
       0.66413729, 0.37592593, 0.0716139 , 0.58986669, 0.19266773,
       0.3317558 , 0.65464267, 0.64804665, 0.73198907, 0.37267798,
       0.47620642, 0.12936016, 0.7207716 , 0.39423479, 0.41694801,
       0.78286885, 0.61986636, 0.03892578, 0.27271521, 0.46977431,
       0.06265665, 0.23558747, 0.10741106, 0.17072951, 0.21303

In [44]:
ar4.size

99

In [45]:
ar4.reshape(11,9)

array([[0.98705175, 0.74422132, 0.18351423, 0.57272625, 0.96688545,
        0.48129732, 0.38639498, 0.73232965, 0.60912908],
       [0.6022489 , 0.84213446, 0.58390546, 0.41510508, 0.55678095,
        0.58955392, 0.96937221, 0.90621632, 0.89905986],
       [0.93664397, 0.47498988, 0.04128258, 0.72282523, 0.19993304,
        0.3083793 , 0.38296473, 0.87088531, 0.62877058],
       [0.45281169, 0.61773935, 0.81031362, 0.25492709, 0.50411477,
        0.63299886, 0.53451714, 0.76921127, 0.74387326],
       [0.61976393, 0.79898007, 0.60865704, 0.29779564, 0.60907677,
        0.13902574, 0.42704775, 0.03010767, 0.89720725],
       [0.09023026, 0.48261823, 0.5995653 , 0.52835164, 0.81413172,
        0.66413729, 0.37592593, 0.0716139 , 0.58986669],
       [0.19266773, 0.3317558 , 0.65464267, 0.64804665, 0.73198907,
        0.37267798, 0.47620642, 0.12936016, 0.7207716 ],
       [0.39423479, 0.41694801, 0.78286885, 0.61986636, 0.03892578,
        0.27271521, 0.46977431, 0.06265665, 0.23558747],


In [46]:
ar4.size

99

In [47]:
ar4.shape

(99,)

In [49]:
arr

array([5, 5])

In [51]:
ar5=np.concatenate((ar2,ar3),axis=1)

In [52]:
ar5

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [53]:
ar6=np.split(ar5,3,axis=1)
ar6

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3, 1],
        [6, 4],
        [9, 7]]),
 array([[ 3, 10],
        [ 5, 12],
        [ 8, 15]])]

In [54]:
np.add(ar5,1)

array([[ 2,  3,  4,  2,  4, 11],
       [ 5,  6,  7,  5,  6, 13],
       [ 8,  9, 10,  8,  9, 16]])

In [55]:
ar7=np.add(ar6[0],ar6[1])
ar7

array([[ 4,  3],
       [10,  9],
       [16, 15]])

In [56]:
ar8=np.multiply(ar6[0],ar6[1])
ar8

array([[ 3,  2],
       [24, 20],
       [63, 56]])